"use client";
import { useState, useTransition } from "react";
import { Button, Card, Image, Input, Segmented, Select, Space, Table, Tag } from "antd";
import { useRouter, useSearchParams } from "next/navigation";
import type { PromotionFacets, PromotionRow, PromotionsPage } from "../domain/promotion.model";
type Props = Readonly<{ page: PromotionsPage; facets: PromotionFacets; catalogError?: boolean; facetsError?: boolean }>;
export function PromotionsView({ page, facets, catalogError = false, facetsError = false }: Props) {
  const router = useRouter(); const current = useSearchParams(); const [mode, setMode] = useState<"Masivo" | "Individual">("Masivo"); const [selected, setSelected] = useState<React.Key[]>([]); const [pending, startTransition] = useTransition();
  const navigate = (key: string, value: string) => { const params = new URLSearchParams(current); params.set(key, value); params.delete("cursor"); params.set("page", "1"); startTransition(() => router.push(`/promociones?${params}`)); };
  const types = [...new Set(page.publications.flatMap((row) => [...row.promotionSummary.activeTypes, ...row.promotionSummary.candidateTypes, ...row.promotionSummary.pendingTypes]))];
  const rows = <Table<PromotionRow> rowSelection={{ type: mode === "Masivo" ? "checkbox" : "radio", selectedRowKeys: selected, onChange: (keys) => setSelected(mode === "Masivo" ? keys : keys.slice(-1)) }} rowKey="itemId" dataSource={[...page.publications]} loading={pending} pagination={false} columns={[{ title: "Imagen", render: (_, row) => row.thumbnail ? <Image alt={row.title} src={row.thumbnail} width={40} preview={false} /> : "—" }, { title: "Producto", dataIndex: "title" }, { title: "MLA", dataIndex: "itemId" }, { title: "Categoría", render: (_, row) => row.category.path.join(" / ") || row.category.name }, { title: "Precio", dataIndex: "price" }, { title: "Promoción actual", render: (_, row) => row.promotionSummary.activeTypes.join(", ") || "—" }, { title: "Estado promoción", render: (_, row) => <Tag>{row.promotionSummary.status === "NONE" ? "Sin promoción" : row.promotionSummary.status === "ACTIVE" ? "Activa" : row.promotionSummary.status === "AVAILABLE" ? "Disponible" : "Pendiente"}</Tag> }, { title: "Acciones", render: () => mode === "Individual" ? <Button>Gestionar promoción</Button> : "—" }]} />;
  return <div style={{ display: "grid", gap: 16 }}>{facetsError ? <p role="alert">No se pudieron cargar los filtros de Mercado Libre.</p> : null}<Segmented options={["Masivo", "Individual"]} value={mode} onChange={(value) => { setMode(value as "Masivo" | "Individual"); setSelected([]); }} /><Card title="Filtrar productos"><Space wrap><Input aria-label="Buscar producto" placeholder="Buscar producto" defaultValue={current.get("search") ?? ""} onPressEnter={(event) => navigate("search", event.currentTarget.value)} /><Select aria-label="Categoría" placeholder="Categoría" allowClear options={facets.categories.map((item) => ({ label: item.path.join(" / ") || item.name, value: item.id }))} onChange={(value) => navigate("categoryId", value ?? "")} />{facets.attributes.map((facet) => <Select key={facet.id} aria-label={facet.name} placeholder={facet.name} allowClear options={facet.values.map((item) => ({ label: item.value, value: `${facet.id}:${item.value}` }))} onChange={(value) => navigate("facetFilters", value ?? "")} />)}</Space></Card><Card title="Filtrar por promociones"><Space wrap><Select aria-label="Estado de promoción" placeholder="Estado de promoción" options={[{ label: "Todas", value: "" }, { label: "Activa", value: "ACTIVE" }, { label: "Disponible", value: "AVAILABLE" }, { label: "Pendiente", value: "PENDING" }, { label: "Sin promoción", value: "NONE" }]} onChange={(value) => navigate("promotionStatus", value)} /><Select aria-label="Tipo de promoción" placeholder="Tipo de promoción" options={types.map((type) => ({ label: type, value: type }))} onChange={(value) => navigate("promotionType", value ?? "")} /></Space></Card>{selected.length > 0 ? <Space><span>{selected.length} publicaciones seleccionadas</span><Button>Cambiar promoción</Button><Button>Quitar promoción</Button></Space> : null}{catalogError ? <p role="alert">No se pudieron cargar las publicaciones de promociones.</p> : page.publications.length === 0 ? <p>{current.get("promotionStatus") || current.get("promotionType") ? "No hay publicaciones que coincidan con estos filtros." : "No se encontraron publicaciones."}</p> : rows}</div>;
}
