"use client";
import { useEffect, useState } from "react";
import { Alert, Button, Card, Modal, Spin, Tag, message } from "antd";
import type { PromotionOption } from "../domain/promotions.repository";
import type { PromotionRow } from "../domain/promotion.model";
import { getPromotionOptions } from "./promotion-options.action";
import { applyPromotion } from "./apply-promotion.action";
type Props = Readonly<{ open: boolean; row: PromotionRow | null; onClose: () => void }>;
const money = (value: number | null) => value == null ? "—" : `$${value.toLocaleString("es-AR")}`;
const displayName = (option: PromotionOption) => option.name ?? ({ PRICE_DISCOUNT: "Descuento en el precio", DEAL: "Oferta especial", SELLER_CAMPAIGN: "Campaña de Mercado Libre", SMART: "Promoción de Mercado Libre" }[option.type?.toUpperCase() ?? ""] ?? "Promoción disponible");
export function PromotionOptionsModal({ open, row, onClose }: Props) {
  const [options, setOptions] = useState<readonly PromotionOption[]>([]); const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle");
  useEffect(() => { if (!open || !row) return; let active = true; void Promise.resolve().then(() => { if (!active) return; setState("loading"); setOptions([]); return getPromotionOptions(row.itemId); }).then((value) => { if (active && value) { setOptions(value); setState("success"); } }).catch(() => { if (active) setState("error"); }); return () => { active = false; }; }, [open, row]);
  const apply = (option: PromotionOption) => Modal.confirm({ title: "¿Aplicar esta promoción?", content: `El producto quedará publicado a ${money(option.promotionPrice)} con ${option.discountPercent ?? 0}% de descuento.`, onOk: async () => { const result = await applyPromotion(row?.itemId ?? "", option); if (!result.ok) { message.error(result.message); throw new Error(result.message); } message.success("Promoción aplicada correctamente."); onClose(); } });
  return <Modal title="Elegir promoción" open={open} onCancel={onClose} footer={null}>{row?.currentPromotion ? <Alert type="warning" message="Esta publicación ya tiene una promoción activa." description="Si elegís otra promoción, primero se quitará la actual y luego se aplicará la nueva." /> : null}{state === "loading" ? <Spin tip="Consultando promociones disponibles..." /> : null}{state === "error" ? <Alert type="error" message="No se pudieron consultar las promociones disponibles." /> : null}{state === "success" && options.length === 0 ? <p>No hay promociones disponibles para esta publicación.</p> : null}{state === "success" ? options.map((option, index) => <Card key={option.id ?? `${option.type ?? "promotion"}-${index}`} title={displayName(option)} size="small"><p><Tag>Disponible</Tag> <small>Tipo: {option.type ?? "—"}</small></p><p><strong>Precio de lista:</strong> {money(option.originalPrice)}</p><p><strong>Descuento para el comprador:</strong> {option.discountPercent == null ? "—" : `${option.discountPercent}%`}</p><p><strong>Ahorro del comprador:</strong> {option.originalPrice != null && option.promotionPrice != null ? `-${money(option.originalPrice - option.promotionPrice)}` : "—"}</p><p><strong>Precio final con promoción:</strong> {money(option.promotionPrice)}</p><p><strong>Costo estimado de Mercado Libre:</strong> {option.saleEstimate ? `-${money(option.saleEstimate.saleFeeAmount)}` : "—"}</p><p><strong>Vos recibís aprox.:</strong> {money(option.saleEstimate?.estimatedNetAmount ?? null)}</p><p>Vigencia: {option.startDate ?? "—"} - {option.finishDate ?? "—"}</p>{option.canApply ? <Button type="primary" onClick={() => apply(option)}>Aplicar esta promoción</Button> : <p>Esta promoción todavía no puede aplicarse desde el panel.</p>}</Card>) : null}</Modal>;
}
